from pipeline.stage_0_add_vital_topics import add_vital_topics
from pipeline.stage_0_add_manual_topics import add_manual_topics
from pipeline.stage_0_add_topics_by_pageviews import add_topics_by_pageviews

from pipeline.stage_1_normalize_topics import normalize_topics

from pipeline.stage_2_filter_topics_by_llm_by_category import filter_topic_by_category
from pipeline.stage_2_filter_topics_by_llm_by_clarity import filter_topic_by_clarity

from pipeline.stage_3_download_wikipedia_pages import download_wikipedia_pages

from pipeline.stage_4_mine_quantities import mine_quantities

from pipeline.stage_5_find_excerpts import find_excerpts

from pipeline.general.add_uuid import add_uuid
from pipeline.general.parallelize import parallelize

from pipeline.stage_6_rewrite_description import rewrite_description
from pipeline.stage_6_filter_clarity import filter_clear, ClarityType
from pipeline.stage_6_filter_correct import filter_correct

from general.generic_filter import generic_filter
from general.deduplicate import deduplicate

from pipeline.stage_7_remove_date_and_unit_from_descriptions import (
    remove_date_and_unit_from_descriptions,
)
from pipeline.stage_7_remove_quantities_with_small_ints import (
    remove_quantities_with_small_ints,
)
from pipeline.stage_7_add_scale_metadata import add_scale_metadata

from pipeline.stage_8_finalize import finalize
